---
title: "Data visualization"
author: "Nathalie Krauth"
date: "6/17/2021"
output: html_document
---
```{r setup}
#load packages
source(here::here("R/package-loading.R"))

#load tidied dataset
load(here::here("data/nhanes_small.rda"))
```

# One variable plot

```{r continuos-variables}
ggplot(nhanes_small, aes(x=bmi)) +
    geom_density()


ggplot(nhanes_small, aes(x=bmi)) +
    geom_histogram()
```

```{r discrete variables}
ggplot(nhanes_small, aes(x=sex)) +
    geom_bar()

ggplot(nhanes_small, aes(x=diabetes)) +
    geom_bar()
```

```{r remove missing-diabetes}

nhanes_tidied <- nhanes_small %>% 
    filter (!is.na(diabetes))

usethis::use_data(nhanes_tidied, overwrite = T)

ggplot(nhanes_tidied, aes(x=diabetes)) +
    geom_bar()
```
# plotting two variables
```{r 2-continous-variables}
bmi_chol <- ggplot(nhanes_tidied, aes (x=bmi, y=tot_chol))

bmi_chol +
    geom_point()

bmi_chol +
    geom_hex()

bmi_chol +
    geom_smooth()
#two graohs on top of each other, first underneath the second
bmi_chol +
    geom_hex() +
    geom_smooth()
```
# two discrete variables
```{r 2-discrete-variables}
two_discrete <- nhanes_tidied %>%    #pipe dataset into ggplot, dont need to write it again
    ggplot(aes(x = diabetes, fill = sex))

two_discrete +
    geom_bar()

# "dodged" (side-by-side) bar plot
two_discrete + 
    geom_bar(position = position_dodge())


```

```{r discrete-continous-variables}
two_mixed <- nhanes_tidied %>% 
    ggplot(aes(x=diabetes, y = bmi))

two_mixed +
    geom_boxplot()
two_mixed +
    geom_jitter()
two_mixed +
    geom_violin()
```

```{r}
# Distribution of age Using geom_histogram(), find out what the distribution is for the two variables below.
ggplot(nhanes_tidied, aes(x = age)) +
    geom_histogram()

ggplot(nhanes_tidied, aes(x = diabetes_age)) +
    geom_histogram()

# 2a. Number of people who smoke now
ggplot(nhanes_tidied, aes(x = smoke_now)) +
    geom_bar()
ggplot(nhanes_tidied, aes(x = phys_active)) +
    geom_bar()

# 3a. BMI in relation to systolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_sys_ave)) +
    geom_hex()

# 3b. BMI relation to diastolic blood pressure
ggplot(nhanes_tidied, aes(x = bmi, y = bp_dia_ave)) +
    geom_hex()

# 4. Physically active people with or without diabetes
ggplot(nhanes_tidied, aes(x = phys_active, fill = diabetes)) +
    geom_bar(position = position_dodge())

# 5. Poverty levels between those with or without diabetes
ggplot(nhanes_tidied, aes(x = diabetes, y = poverty)) +
    geom_violin()
```

#plotting three or more variables
```{r using-colour}
nhanes_tidied %>% 
    ggplot(aes(x = sex, y= bp_sys_ave, colour = diabetes)) +
    geom_boxplot()

# 3 continous variables
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = age)) +
    geom_point()

# 2 continous and 1 discrete variable
nhanes_tidied %>% 
    ggplot(aes(x = bmi, y = bp_sys_ave, colour = diabetes)) +
    geom_point()
```

```{r faceting}
nhanes_tidied %>% 
    ggplot(aes(x=bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(cols = vars(diabetes))

#stacked instead of side by side:
nhanes_tidied %>% 
    ggplot(aes(x=bmi, y = bp_sys_ave)) +
    geom_point() +
    facet_grid(rows = vars(diabetes))

# 5 variables
nhanes_tidied %>% 
    ggplot(aes(x=bmi, y = bp_sys_ave, colour = age)) +
    geom_point() +
    facet_grid(rows = vars(diabetes), cols = vars (sex))

```


